# Build options
[buildOptions]
optimizeWithTtx = false

# Building plans
# Sans
[buildPlans.iocursive-sans-type]
family = "IoCursive Sans Type"

[buildPlans.iocursive-sans-term]
family = "IoCursive Sans Term"
spacing = "term"

[buildPlans.iocursive-sans-fixed]
family = "IoCursive Sans Fixed"
spacing = "fixed"

# Slab
[buildPlans.iocursive-slab-type]
family = "IoCursive Slab Type"
serifs = "slab"

[buildPlans.iocursive-slab-term]
family = "IoCursive Slab Term"
serifs = "slab"
spacing = "term"

[buildPlans.iocursive-slab-fixed]
family = "IoCursive Slab Fixed"
serifs = "slab"
spacing = "fixed"

###################################################################################################
# Proportional families

[buildPlans.iocursive-slab]
family  = "IoCursive Slab"
spacing = "quasi-proportional"
serifs = 'slab'

[buildPlans.iocursive-slab.variants.design]
at = 'fourfold'
capital-w = 'straight-flat-top'
f = "flat-hook-serifed"
j = 'flat-hook-serifed'
t = "flat-hook"
w = 'straight-flat-top'

[buildPlans.iocursive-slab.variants.italic]
f = "flat-hook-tailed"

# Letterform control for U+1D670 ... U+1D6A3
[buildPlans.iocursive-slab.derivingVariants.mathtt.design]
at = 'threefold'
capital-w = 'straight-flat-top'
f = "flat-hook-serifed"
j = 'flat-hook-serifed'
t = "flat-hook"
w = 'straight-flat-top'

[buildPlans.iocursive-slab.derivingVariants.mathtt.italic]
f = "flat-hook-tailed"


###################################################################################################
# Collect plans

[collectPlans.iocursive]
release = true
from = [
	"iocursive-sans-type",
	"iocursive-sans-term",
	"iocursive-sans-fixed",
	"iocursive-slab",
	"iocursive-slab-type",
	"iocursive-slab-term",
	"iocursive-slab-fixed"
]

[collectConfig]
distinguishWeights = true
distinguishWidths = true
distinguishSlope = true

###################################################################################################
# Weight mappings (style => shape weight, menu weight, CSS weight)
#   Shape weight : affects the shape of the glyphs
#   Menu weight  : affects the font menu name
#   CSS weight   : affects the webfont CSS "font-weight" property
# IMPORTANT : Currently "menu" property only support 100, 200, 300, 400, 500, 600, 700, 800, 900.
#              and "shape" properly only supports number between 100 and 900 (inclusive).

[weights.thin]
shape = 100
menu  = 100
css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.semilight]
shape = 350
menu  = 350
css   = 350

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.book]
shape = 450
menu  = 450
css   = 450

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# slope mappings (style => CSS)
# NOTE: This mapping does NOT affect the font's metadata, only affects
#       the webfont CSS. Change `params/parameters.toml` instead.
[slopes]
cursive = "normal"
italic = "italic"

# Width mappings (style => shape width, menu width, CSS stretch)
#   Shape width   : affects the shape of the glyphs
#   Menu width    : affects the font menu name
#   CSS stretch   : affects the webfont CSS "font-stretch" property
#
# IMPORTANT : Currently "shape" property only support 3 ... 9
#              and "menu" only support 1 ... 9

[widths.normal]
shape = 500
menu  = 5
css   = "normal"

[widths.extended]
shape = 600
menu  = 7
css   = "expanded"
